services:
  # PostgreSQL (User, Product, Order)
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
  
  # Couchbase (Cart)    
  couchbase-db:
    image: couchbase:community-7.1.1
    container_name: couchbase-db
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    env_file:
      - .env
    volumes:
      - couchbase_data:/opt/couchbase/var
    networks:
      - ecommerce-network
  
  # Couchbase Setup    
  init-couchbase:
    build:
      context: ./couchbase-init
      dockerfile: Dockerfile
    image: ecommerce/couchbase-init
    container_name: init-couchbase
    depends_on:
      - couchbase-db
    env_file:
      - .env
    networks:
      - ecommerce-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:4.1.3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-network

  # Jaeger - Distributed Tracing
  jaeger-tracer:
    image: jaegertracing/all-in-one:1.72.0
    container_name: jaeger-tracer
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - ecommerce-network

  # Redis - Caching
  redis-cache:
    image: redis:8.2.0
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

  # Prometheus - Metrics Gathering
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ecommerce-network

  # Grafana - Metrics Visualization - ID 14331
  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - ecommerce-network

  # ------------ GO SERVICES ------------ #
  api-gateway:
    container_name: api-gateway
    image: ogozo/api-gateway:1.0
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network
    depends_on:
      - service-user
      - service-product
      - service-cart
      - service-order
    env_file:
      - ./env/gateway.env

  service-user:
    container_name: service-user
    image: ogozo/service-user:1.0
    build:
      context: ../service-user
      dockerfile: Dockerfile
    networks:
      - ecommerce-network
    depends_on:
      - postgres-db
    env_file:
      - ./env/user.env

  service-product:
    container_name: service-product
    image: ogozo/service-product:1.0
    build:
      context: ../service-product
      dockerfile: Dockerfile
    networks:
      - ecommerce-network
    depends_on:
      - postgres-db
      - redis-cache
    env_file:
      - ./env/product.env

  service-cart:
    container_name: service-cart
    image: ogozo/service-cart:1.0
    build:
      context: ../service-cart
      dockerfile: Dockerfile
    networks:
      - ecommerce-network
    depends_on:
      - init-couchbase
    env_file:
      - ./env/cart.env
      
  service-order:
    container_name: service-order
    image: ogozo/service-order:1.0
    build:
      context: ../service-order
      dockerfile: Dockerfile
    networks:
      - ecommerce-network
    depends_on:
      - postgres-db
      - rabbitmq
    env_file:
      - ./env/order.env

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
  couchbase_data:
  prometheus_data:
  grafana_data:
