global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'e-commerce-services'
    static_configs:
      - targets:
        - 'api-gateway:3000'
        - 'service-user:9001'
        - 'service-product:9002'
        - 'service-cart:9003'
        - 'service-order:9004'